# Generated by Django 5.1.6 on 2025-03-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('artwork_status', models.IntegerField(default=0)),
                ('artwork_price', models.CharField(max_length=30)),
                ('artwork_description', models.CharField(max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_artist')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_auctionhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionhead_amount', models.CharField(max_length=30)),
                ('auctionhead_date', models.DateField(auto_now_add=True)),
                ('auctionhead_todate', models.DateField()),
                ('auction_starttime', models.CharField(max_length=30)),
                ('auctionhead_status', models.IntegerField(default=0)),
                ('auction_totalamount', models.CharField(max_length=30)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.tbl_artwork')),
            ],
        ),
    ]
